version: "3.8"
services:
  web:
    depends_on:
      - postgres_db
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    env_file:
      - .env
  postgres_db:
    image: postgres
    restart: always
    # command: -p 5433
    platform: linux/amd64
    env_file:
      - .env
    # expose:
    #   - 5433
    # ports:
    #   - 5433:5433

    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
