version: '3.8'
services:
  web:
    depends_on:
      - postgres_db
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    ports:
      - "8000:8000"
    image: j30v/django-devia2
    volumes:
      - ./:/app
    env_file:
      - .env
  postgres_db:
    image: postgres
    restart: always
    platform: linux/amd64
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
