version: '3.8'
services:
  web:
    ports:
      - "8000:8000"
    image: j30v/django-devia2
    env_file:
      - .env
  postgresdb:
    hostname:
    image: postgres:11.19-alpine
    restart: always
    env_file:
      - .envpostgres
    ports:
      - "5433:5433"
    volumes:
      - postgresdata:/var/lib/postgresql/data/
volumes:
  postgresdata:
    driver: azure_file
    driver_opts:
      share_name: fileshare1
      storage_account_name: storagejv2
